[package]
name = "container-runtime"
version = "0.71.0"
authors = ["Sergii Mikhtoniuk <mikhtoniuk@gmail.com>"]
edition = "2021"
license-file = "../../LICENSE.txt"

[features]
skip_docker_tests = []

[dependencies]
dill = { version = "~0.2.0" }
regex = "*"
serde = { version = "*", features = ["derive"] }
thiserror = "*"
url = "*"
