[package]
name = "container-runtime"
version = "0.105.0"
authors = ["Sergii Mikhtoniuk <mikhtoniuk@gmail.com>"]
edition = "2021"
license-file = "../../LICENSE.txt"

[features]
skip_docker_tests = []

[dependencies]
dill = "~0.3"
regex = "*"
serde = { version = "*", features = ["derive"] }
thiserror = "*"
url = "*"
