[package]
name = "kamu-adapter-graphql"
version = "0.81.0"
authors = ["Sergii Mikhtoniuk <mikhtoniuk@gmail.com>"]
edition = "2021"

[dependencies]
# Kamu
dill = "~0.3"
opendatafabric = { path = "../opendatafabric" }
kamu = { path = "../kamu-core" }

# HTTP
# TODO: Remove from this crate
reqwest = { version = "*", features = ["json"] }

# GraphQL
async-graphql = { version = "*", features = ["chrono", "url", "apollo_tracing"] }

# Utils
chrono = "*"
datafusion = "*"  # TODO: Currently needed for type conversions but ideally should be encapsulated by kamu-core
serde = "*"
serde_json = "*"
# tokio = { version = "*", features = ["macros"] }
# url = "*"


[dev-dependencies]
tempfile = "*"
tokio = { version = "*" }
