[package]
name = "kamu-adapter-graphql"
version = "0.114.1"
authors = ["Sergii Mikhtoniuk <mikhtoniuk@gmail.com>"]
edition = "2021"

[lib]
doctest = false

[dependencies]
# Kamu
dill = "~0.3"
opendatafabric = { path = "../opendatafabric" }
kamu = { path = "../kamu-core" }

# HTTP
# TODO: Remove from this crate
reqwest = { version = "*", features = ["json"] }

# GraphQL
async-graphql = { version = "*", features = ["chrono", "url", "apollo_tracing"] }

# Utils
indoc = "*"
chrono = "*"
datafusion = "19"  # TODO: Currently needed for type conversions but ideally should be encapsulated by kamu-core
futures = "*"
serde = "*"
serde_json = "*"
tracing = "*"
# tokio = { version = "*", features = ["macros"] }
# url = "*"


[dev-dependencies]
tempfile = "*"
tokio = { version = "*" }
env_logger = "*"
test-log = { version = "*", features = ["trace"] }
tracing-subscriber = { version = "*", features = ["env-filter"] }
