[package]
name = "opendatafabric"
version = "0.62.1"
authors = ["Sergii Mikhtoniuk <mikhtoniuk@gmail.com>"]
edition = "2018"

[dependencies]
# Domain
chrono = { version = "*", features = ["serde"] }
intervals-general = "*"
rust-crypto = "*"  # Data and metadata hashing

# Serialization
byteorder = "*"
flatbuffers = "*"
hex = "*"
serde = { version = "*", features = ["derive"] }
serde_with = "*"
serde_yaml = "*"

# Utils
indoc = "*"  # Compile-time unindent
thiserror = "*"  # Structured error derivations
