[package]
name = "opendatafabric"
description = "Implements core conecpts of Open Data Fabric protocol specification"
version = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
readme = { workspace = true }
license-file = { workspace = true }
keywords = { workspace = true }
include = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }


[lib]
doctest = false


[dependencies]
enum-variants = { workspace = true }
internal-error = { workspace = true }

chrono = { version = "0.4", features = ["serde"] }
indoc = "2"
futures-core = "0.3"
thiserror = { version = "=1.0.44", default-features = false }  # TODO: Pinned until rustc upgrade

# Multiformats
bs58 = "0.5"  # base58 codec
digest = "0.10"
sha3 = "0.10"
unsigned-varint = "0.8"
url = "2"

# Crypto
ed25519-dalek = { version = "2", default-features = false, features = ["std", "fast", "rand_core"] }
rand = "0.8"  # TODO: Pinned for ed25519-dalek compatibility

# Serialization
byteorder = "1"
flatbuffers = "23"
hex = "0.4"
serde = { version = "1", features = ["derive"] }
serde_with = "3"
serde_yaml = "0.9"

# gRPC
prost = "0.12"
tonic = "0.10"
