[package]
name = "tools"
version = "0.0.0"
description = "Tools for managing this repo"
edition = "2021"

[[bin]]
name = "release"
path = "src/release.rs"

[[bin]]
name = "create-test-workspace"
path = "src/create_test_workspace.rs"

[dependencies]
clap = "*"
chrono = "*"
glob = "*"
regex = "*"
semver = "*"
toml = "*"
toml_edit = "*"
url = "*"
yaml-rust = "*"

[dev-dependencies]
indoc = "*"
