name: release-images-with-data
on:
  # Triggered upon completion of `release-images`
  workflow_dispatch:
    inputs:
      release_sha:
        description: "Git SHA from the original release workflow"
        required: true
        type: string
env:
  # AWS credentials (needed only to list a bucket)
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-west-2
jobs:
  build_images:
    name: Build Images With Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          # Checkout the same commit that the release was built for
          ref: ${{ inputs.release_sha }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images with sample data
        run: |
          cd images/
          make kamu-base-with-data
          make kamu-base-with-data-mt

      - name: Publish images
        run: |
          cd images
          make kamu-base-with-data-push
          make kamu-base-with-data-mt-push
